export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          display_name: string;
          avatar_url: string | null;
          birth_date: string | null;
          attachment_style: 'secure' | 'anxious' | 'avoidant' | 'disorganized' | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          display_name: string;
          avatar_url?: string | null;
          birth_date?: string | null;
          attachment_style?: 'secure' | 'anxious' | 'avoidant' | 'disorganized' | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          display_name?: string;
          avatar_url?: string | null;
          birth_date?: string | null;
          attachment_style?: 'secure' | 'anxious' | 'avoidant' | 'disorganized' | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_psychology_profiles: {
        Row: {
          id: string;
          user_id: string;
          attachment_style: 'secure' | 'anxious' | 'avoidant' | 'disorganized';
          attachment_security_score: number | null;
          attachment_anxiety_score: number | null;
          attachment_avoidance_score: number | null;
          primary_love_language: 'words_of_affirmation' | 'quality_time' | 'physical_touch' | 'acts_of_service' | 'receiving_gifts';
          secondary_love_language: 'words_of_affirmation' | 'quality_time' | 'physical_touch' | 'acts_of_service' | 'receiving_gifts' | null;
          love_language_scores: any | null;
          gottman_assessment_score: number | null;
          four_horsemen_tendencies: any | null;
          gottman_strengths: string[] | null;
          cognitive_distortions: string[] | null;
          cbt_progress_score: number | null;
          thought_challenging_skills: number | null;
          emotional_regulation_score: number | null;
          distress_tolerance_score: number | null;
          interpersonal_effectiveness_score: number | null;
          mindfulness_score: number | null;
          emotional_awareness_score: number | null;
          emotional_expression_score: number | null;
          attachment_injury_areas: string[] | null;
          psychological_flexibility_score: number | null;
          core_values: any | null;
          values_living_score: number | null;
          character_strengths: string[] | null;
          gratitude_practice_frequency: number | null;
          life_satisfaction_score: number | null;
          body_awareness_score: number | null;
          somatic_preferences: any | null;
          trauma_informed_needs: boolean | null;
          relationship_narrative: any | null;
          preferred_narrative_identity: string | null;
          externalized_problems: string[] | null;
          relationship_goals: any | null;
          scaling_scores: any | null;
          exceptions_catalog: any | null;
          meditation_experience: 'none' | 'beginner' | 'intermediate' | 'advanced' | null;
          mindfulness_practice_frequency: number | null;
          preferred_mindfulness_techniques: string[] | null;
          assessment_completion_percentage: number | null;
          last_assessment_update: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          attachment_style: 'secure' | 'anxious' | 'avoidant' | 'disorganized';
          attachment_security_score?: number | null;
          attachment_anxiety_score?: number | null;
          attachment_avoidance_score?: number | null;
          primary_love_language: 'words_of_affirmation' | 'quality_time' | 'physical_touch' | 'acts_of_service' | 'receiving_gifts';
          secondary_love_language?: 'words_of_affirmation' | 'quality_time' | 'physical_touch' | 'acts_of_service' | 'receiving_gifts' | null;
          love_language_scores?: any | null;
          gottman_assessment_score?: number | null;
          four_horsemen_tendencies?: any | null;
          gottman_strengths?: string[] | null;
          cognitive_distortions?: string[] | null;
          cbt_progress_score?: number | null;
          thought_challenging_skills?: number | null;
          emotional_regulation_score?: number | null;
          distress_tolerance_score?: number | null;
          interpersonal_effectiveness_score?: number | null;
          mindfulness_score?: number | null;
          emotional_awareness_score?: number | null;
          emotional_expression_score?: number | null;
          attachment_injury_areas?: string[] | null;
          psychological_flexibility_score?: number | null;
          core_values?: any | null;
          values_living_score?: number | null;
          character_strengths?: string[] | null;
          gratitude_practice_frequency?: number | null;
          life_satisfaction_score?: number | null;
          body_awareness_score?: number | null;
          somatic_preferences?: any | null;
          trauma_informed_needs?: boolean | null;
          relationship_narrative?: any | null;
          preferred_narrative_identity?: string | null;
          externalized_problems?: string[] | null;
          relationship_goals?: any | null;
          scaling_scores?: any | null;
          exceptions_catalog?: any | null;
          meditation_experience?: 'none' | 'beginner' | 'intermediate' | 'advanced' | null;
          mindfulness_practice_frequency?: number | null;
          preferred_mindfulness_techniques?: string[] | null;
          assessment_completion_percentage?: number | null;
          last_assessment_update?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          attachment_style?: 'secure' | 'anxious' | 'avoidant' | 'disorganized';
          attachment_security_score?: number | null;
          attachment_anxiety_score?: number | null;
          attachment_avoidance_score?: number | null;
          primary_love_language?: 'words_of_affirmation' | 'quality_time' | 'physical_touch' | 'acts_of_service' | 'receiving_gifts';
          secondary_love_language?: 'words_of_affirmation' | 'quality_time' | 'physical_touch' | 'acts_of_service' | 'receiving_gifts' | null;
          love_language_scores?: any | null;
          gottman_assessment_score?: number | null;
          four_horsemen_tendencies?: any | null;
          gottman_strengths?: string[] | null;
          cognitive_distortions?: string[] | null;
          cbt_progress_score?: number | null;
          thought_challenging_skills?: number | null;
          emotional_regulation_score?: number | null;
          distress_tolerance_score?: number | null;
          interpersonal_effectiveness_score?: number | null;
          mindfulness_score?: number | null;
          emotional_awareness_score?: number | null;
          emotional_expression_score?: number | null;
          attachment_injury_areas?: string[] | null;
          psychological_flexibility_score?: number | null;
          core_values?: any | null;
          values_living_score?: number | null;
          character_strengths?: string[] | null;
          gratitude_practice_frequency?: number | null;
          life_satisfaction_score?: number | null;
          body_awareness_score?: number | null;
          somatic_preferences?: any | null;
          trauma_informed_needs?: boolean | null;
          relationship_narrative?: any | null;
          preferred_narrative_identity?: string | null;
          externalized_problems?: string[] | null;
          relationship_goals?: any | null;
          scaling_scores?: any | null;
          exceptions_catalog?: any | null;
          meditation_experience?: 'none' | 'beginner' | 'intermediate' | 'advanced' | null;
          mindfulness_practice_frequency?: number | null;
          preferred_mindfulness_techniques?: string[] | null;
          assessment_completion_percentage?: number | null;
          last_assessment_update?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      couples: {
        Row: {
          id: string;
          partner1_id: string;
          partner2_id: string;
          relationship_start_date: string | null;
          relationship_status: 'dating' | 'engaged' | 'married' | 'partnership' | null;
          health_score: number;
          current_streak: number;
          longest_streak: number;
          goals: string[] | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          partner1_id: string;
          partner2_id: string;
          relationship_start_date?: string | null;
          relationship_status?: 'dating' | 'engaged' | 'married' | 'partnership' | null;
          health_score?: number;
          current_streak?: number;
          longest_streak?: number;
          goals?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          partner1_id?: string;
          partner2_id?: string;
          relationship_start_date?: string | null;
          relationship_status?: 'dating' | 'engaged' | 'married' | 'partnership' | null;
          health_score?: number;
          current_streak?: number;
          longest_streak?: number;
          goals?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      daily_questions: {
        Row: {
          id: string;
          couple_id: string;
          content: string;
          category: 'values' | 'memories' | 'future' | 'intimacy' | 'conflict' | 'gratitude';
          difficulty_level: number;
          ai_generated: boolean;
          date: string;
          created_at: string;
        };
        Insert: {
          id: string;
          couple_id: string;
          content: string;
          category: 'values' | 'memories' | 'future' | 'intimacy' | 'conflict' | 'gratitude';
          difficulty_level: number;
          ai_generated?: boolean;
          date: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          couple_id?: string;
          content?: string;
          category?: 'values' | 'memories' | 'future' | 'intimacy' | 'conflict' | 'gratitude';
          difficulty_level?: number;
          ai_generated?: boolean;
          date?: string;
          created_at?: string;
        };
      };
      responses: {
        Row: {
          id: string;
          question_id: string;
          user_id: string;
          content: string;
          is_private: boolean;
          timestamp: string;
          created_at: string;
        };
        Insert: {
          id: string;
          question_id: string;
          user_id: string;
          content: string;
          is_private?: boolean;
          timestamp: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          question_id?: string;
          user_id?: string;
          content?: string;
          is_private?: boolean;
          timestamp?: string;
          created_at?: string;
        };
      };
      reflections: {
        Row: {
          id: string;
          user_id: string;
          content_encrypted: string;
          mood: 'happy' | 'sad' | 'anxious' | 'excited' | 'confused' | 'grateful' | 'frustrated' | null;
          tags: string[] | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          user_id: string;
          content_encrypted: string;
          mood?: 'happy' | 'sad' | 'anxious' | 'excited' | 'confused' | 'grateful' | 'frustrated' | null;
          tags?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          content_encrypted?: string;
          mood?: 'happy' | 'sad' | 'anxious' | 'excited' | 'confused' | 'grateful' | 'frustrated' | null;
          tags?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      quests: {
        Row: {
          id: string;
          couple_id: string;
          quest_type: string;
          title: string;
          description: string;
          duration_days: number;
          progress: number;
          is_completed: boolean;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          couple_id: string;
          quest_type: string;
          title: string;
          description: string;
          duration_days: number;
          progress?: number;
          is_completed?: boolean;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          couple_id?: string;
          quest_type?: string;
          title?: string;
          description?: string;
          duration_days?: number;
          progress?: number;
          is_completed?: boolean;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      crisis_events: {
        Row: {
          id: string;
          couple_id: string;
          event_hash: string;
          severity: 'low' | 'medium' | 'high' | 'critical';
          timestamp: string;
          created_at: string;
        };
        Insert: {
          id: string;
          couple_id: string;
          event_hash: string;
          severity: 'low' | 'medium' | 'high' | 'critical';
          timestamp: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          couple_id?: string;
          event_hash?: string;
          severity?: 'low' | 'medium' | 'high' | 'critical';
          timestamp?: string;
          created_at?: string;
        };
      };
      invitations: {
        Row: {
          id: string;
          inviter_id: string;
          invite_code: string;
          couple_id: string | null;
          email: string | null;
          status: 'pending' | 'accepted' | 'expired';
          expires_at: string;
          created_at: string;
        };
        Insert: {
          id: string;
          inviter_id: string;
          invite_code: string;
          couple_id?: string | null;
          email?: string | null;
          status?: 'pending' | 'accepted' | 'expired';
          expires_at: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          inviter_id?: string;
          invite_code?: string;
          couple_id?: string | null;
          email?: string | null;
          status?: 'pending' | 'accepted' | 'expired';
          expires_at?: string;
          created_at?: string;
        };
      };
      couple_psychology_analysis: {
        Row: {
          id: string;
          couple_id: string;
          attachment_compatibility_score: number | null;
          attachment_challenges: any | null;
          attachment_strengths: any | null;
          communication_style_match: number | null;
          conflict_resolution_compatibility: number | null;
          emotional_expression_alignment: number | null;
          love_language_compatibility_score: number | null;
          love_language_recommendations: any | null;
          core_values_alignment: number | null;
          shared_values: string[] | null;
          values_conflicts: any | null;
          strengths_compatibility: number | null;
          complementary_strengths: string[] | null;
          shared_strengths: string[] | null;
          recommended_modalities: string[] | null;
          priority_focus_areas: string[] | null;
          suggested_interventions: any | null;
          overall_compatibility_score: number | null;
          compatibility_trend: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          couple_id: string;
          attachment_compatibility_score?: number | null;
          attachment_challenges?: any | null;
          attachment_strengths?: any | null;
          communication_style_match?: number | null;
          conflict_resolution_compatibility?: number | null;
          emotional_expression_alignment?: number | null;
          love_language_compatibility_score?: number | null;
          love_language_recommendations?: any | null;
          core_values_alignment?: number | null;
          shared_values?: string[] | null;
          values_conflicts?: any | null;
          strengths_compatibility?: number | null;
          complementary_strengths?: string[] | null;
          shared_strengths?: string[] | null;
          recommended_modalities?: string[] | null;
          priority_focus_areas?: string[] | null;
          suggested_interventions?: any | null;
          overall_compatibility_score?: number | null;
          compatibility_trend?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          couple_id?: string;
          attachment_compatibility_score?: number | null;
          attachment_challenges?: any | null;
          attachment_strengths?: any | null;
          communication_style_match?: number | null;
          conflict_resolution_compatibility?: number | null;
          emotional_expression_alignment?: number | null;
          love_language_compatibility_score?: number | null;
          love_language_recommendations?: any | null;
          core_values_alignment?: number | null;
          shared_values?: string[] | null;
          values_conflicts?: any | null;
          strengths_compatibility?: number | null;
          complementary_strengths?: string[] | null;
          shared_strengths?: string[] | null;
          recommended_modalities?: string[] | null;
          priority_focus_areas?: string[] | null;
          suggested_interventions?: any | null;
          overall_compatibility_score?: number | null;
          compatibility_trend?: number | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      psychology_interventions: {
        Row: {
          id: string;
          title: string;
          description: string;
          instructions: any;
          modality: 'cbt' | 'dbt' | 'eft' | 'act' | 'mindfulness' | 'positive_psychology' | 'somatic' | 'narrative' | 'sfbt' | 'gottman' | 'attachment';
          target_issues: string[] | null;
          required_skills: string[] | null;
          contraindications: string[] | null;
          attachment_styles: string[] | null;
          relationship_stages: string[] | null;
          difficulty_level: number | null;
          duration_minutes: number | null;
          frequency_per_week: number | null;
          total_sessions: number | null;
          evidence_base: string | null;
          created_by: string | null;
          is_active: boolean | null;
          tags: string[] | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description: string;
          instructions: any;
          modality: 'cbt' | 'dbt' | 'eft' | 'act' | 'mindfulness' | 'positive_psychology' | 'somatic' | 'narrative' | 'sfbt' | 'gottman' | 'attachment';
          target_issues?: string[] | null;
          required_skills?: string[] | null;
          contraindications?: string[] | null;
          attachment_styles?: string[] | null;
          relationship_stages?: string[] | null;
          difficulty_level?: number | null;
          duration_minutes?: number | null;
          frequency_per_week?: number | null;
          total_sessions?: number | null;
          evidence_base?: string | null;
          created_by?: string | null;
          is_active?: boolean | null;
          tags?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string;
          instructions?: any;
          modality?: 'cbt' | 'dbt' | 'eft' | 'act' | 'mindfulness' | 'positive_psychology' | 'somatic' | 'narrative' | 'sfbt' | 'gottman' | 'attachment';
          target_issues?: string[] | null;
          required_skills?: string[] | null;
          contraindications?: string[] | null;
          attachment_styles?: string[] | null;
          relationship_stages?: string[] | null;
          difficulty_level?: number | null;
          duration_minutes?: number | null;
          frequency_per_week?: number | null;
          total_sessions?: number | null;
          evidence_base?: string | null;
          created_by?: string | null;
          is_active?: boolean | null;
          tags?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_intervention_progress: {
        Row: {
          id: string;
          user_id: string;
          couple_id: string;
          intervention_id: string;
          status: 'not_started' | 'in_progress' | 'completed' | 'paused' | 'discontinued' | null;
          current_session: number | null;
          completion_percentage: number | null;
          pre_intervention_score: number | null;
          current_score: number | null;
          post_intervention_score: number | null;
          user_rating: number | null;
          user_feedback: string | null;
          perceived_helpfulness: number | null;
          started_at: string | null;
          last_session_at: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          couple_id: string;
          intervention_id: string;
          status?: 'not_started' | 'in_progress' | 'completed' | 'paused' | 'discontinued' | null;
          current_session?: number | null;
          completion_percentage?: number | null;
          pre_intervention_score?: number | null;
          current_score?: number | null;
          post_intervention_score?: number | null;
          user_rating?: number | null;
          user_feedback?: string | null;
          perceived_helpfulness?: number | null;
          started_at?: string | null;
          last_session_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          couple_id?: string;
          intervention_id?: string;
          status?: 'not_started' | 'in_progress' | 'completed' | 'paused' | 'discontinued' | null;
          current_session?: number | null;
          completion_percentage?: number | null;
          pre_intervention_score?: number | null;
          current_score?: number | null;
          post_intervention_score?: number | null;
          user_rating?: number | null;
          user_feedback?: string | null;
          perceived_helpfulness?: number | null;
          started_at?: string | null;
          last_session_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      daily_psychological_checkins: {
        Row: {
          id: string;
          user_id: string;
          couple_id: string;
          date: string;
          primary_emotion: 'joy' | 'sadness' | 'anger' | 'fear' | 'disgust' | 'surprise' | 'shame' | 'guilt' | 'excitement' | 'contentment' | 'anxiety' | 'love' | null;
          emotion_intensity: number | null;
          secondary_emotions: string[] | null;
          relationship_satisfaction: number | null;
          connection_feeling: number | null;
          communication_quality: number | null;
          conflict_level: number | null;
          mindfulness_minutes: number | null;
          gratitude_items: string[] | null;
          values_alignment_today: number | null;
          emotional_regulation_success: number | null;
          personal_notes: string | null;
          wins_today: string[] | null;
          challenges_today: string[] | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          couple_id: string;
          date: string;
          primary_emotion?: 'joy' | 'sadness' | 'anger' | 'fear' | 'disgust' | 'surprise' | 'shame' | 'guilt' | 'excitement' | 'contentment' | 'anxiety' | 'love' | null;
          emotion_intensity?: number | null;
          secondary_emotions?: string[] | null;
          relationship_satisfaction?: number | null;
          connection_feeling?: number | null;
          communication_quality?: number | null;
          conflict_level?: number | null;
          mindfulness_minutes?: number | null;
          gratitude_items?: string[] | null;
          values_alignment_today?: number | null;
          emotional_regulation_success?: number | null;
          personal_notes?: string | null;
          wins_today?: string[] | null;
          challenges_today?: string[] | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          couple_id?: string;
          date?: string;
          primary_emotion?: 'joy' | 'sadness' | 'anger' | 'fear' | 'disgust' | 'surprise' | 'shame' | 'guilt' | 'excitement' | 'contentment' | 'anxiety' | 'love' | null;
          emotion_intensity?: number | null;
          secondary_emotions?: string[] | null;
          relationship_satisfaction?: number | null;
          connection_feeling?: number | null;
          communication_quality?: number | null;
          conflict_level?: number | null;
          mindfulness_minutes?: number | null;
          gratitude_items?: string[] | null;
          values_alignment_today?: number | null;
          emotional_regulation_success?: number | null;
          personal_notes?: string | null;
          wins_today?: string[] | null;
          challenges_today?: string[] | null;
          created_at?: string;
        };
      };
      psychology_assessments: {
        Row: {
          id: string;
          user_id: string;
          assessment_type: string;
          questions_responses: any;
          raw_scores: any | null;
          interpreted_results: any | null;
          assessment_version: string | null;
          completion_time_seconds: number | null;
          is_complete: boolean | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          assessment_type: string;
          questions_responses: any;
          raw_scores?: any | null;
          interpreted_results?: any | null;
          assessment_version?: string | null;
          completion_time_seconds?: number | null;
          is_complete?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          assessment_type?: string;
          questions_responses?: any;
          raw_scores?: any | null;
          interpreted_results?: any | null;
          assessment_version?: string | null;
          completion_time_seconds?: number | null;
          is_complete?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      attachment_style: 'secure' | 'anxious' | 'avoidant' | 'disorganized';
      relationship_status: 'dating' | 'engaged' | 'married' | 'partnership';
      question_category: 'values' | 'memories' | 'future' | 'intimacy' | 'conflict' | 'gratitude';
      mood_type: 'happy' | 'sad' | 'anxious' | 'excited' | 'confused' | 'grateful' | 'frustrated';
      crisis_severity: 'low' | 'medium' | 'high' | 'critical';
      invitation_status: 'pending' | 'accepted' | 'expired';
      love_language: 'words_of_affirmation' | 'quality_time' | 'physical_touch' | 'acts_of_service' | 'receiving_gifts';
      gottman_horseman: 'criticism' | 'contempt' | 'defensiveness' | 'stonewalling';
      emotional_state: 'joy' | 'sadness' | 'anger' | 'fear' | 'disgust' | 'surprise' | 'shame' | 'guilt' | 'excitement' | 'contentment' | 'anxiety' | 'love';
      therapy_modality: 'cbt' | 'dbt' | 'eft' | 'act' | 'mindfulness' | 'positive_psychology' | 'somatic' | 'narrative' | 'sfbt' | 'gottman' | 'attachment';
      personality_strength: 'curiosity' | 'judgment' | 'love_of_learning' | 'perspective' | 'bravery' | 'perseverance' | 'honesty' | 'zest' | 'love' | 'kindness' | 'social_intelligence' | 'teamwork' | 'fairness' | 'leadership' | 'forgiveness' | 'humility' | 'prudence' | 'self_regulation' | 'appreciation_of_beauty' | 'gratitude' | 'hope' | 'humor' | 'spirituality';
    };
  };
};